services:
  - type: web
    name: cam-database
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: cam-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cam-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cam-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: cam-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cam-postgres
          property: password

databases:
  - name: cam-postgres
    plan: free
    databaseName: cam_database 