services:
  - type: web
    name: cam-server
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node scripts/start-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
    disk:
      name: cam-data
      mountPath: /data
    autoDeploy: true

databases:
  - name: cam-postgres
    plan: free
    databaseName: cam_database 