services:
  - type: web
    name: cam-server
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node scripts/start-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: cam-postgres
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: cam-postgres
    databaseName: cam_db
    user: cam_user
    plan: free 